using System;
using Framework.Asset;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Example
{
    /// <summary>
    /// Creates a visible scene instance through the framework's Addressables path.
    /// The prefab and its Addressables entry are generated by the companion editor setup.
    /// </summary>
    public static class AddressablePrefabDemo
    {
        public const string AssetKey = "demo/addressable-prefab";
        public const string InstanceRootName = "[Addressable Instances]";

        private static bool spawnRequested;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static async void SpawnAfterSceneLoad()
        {
            if (SceneManager.GetActiveScene().name != "AddressableDemo")
            {
                return;
            }

            if (spawnRequested || GameObject.Find(InstanceRootName) != null)
            {
                return;
            }

            spawnRequested = true;

            try
            {
                AssetLoader.RegisterDefinition(
                    new AssetDefinition(AssetKey, AssetKey, AssetSource.Addressables));

                var root = new GameObject(InstanceRootName);
                var instance = await AssetLoader.InstantiateAsync(
                    AssetKey,
                    root.transform,
                    AssetSource.Addressables);

                if (instance == null)
                {
                    UnityEngine.Object.Destroy(root);
                    Debug.LogError($"[AddressablePrefabDemo] Failed to instantiate '{AssetKey}'.");
                    return;
                }

                instance.name = "Addressable Demo Instance";
                instance.transform.localPosition = Vector3.zero;
                instance.transform.localRotation = Quaternion.Euler(20f, 30f, 10f);
                Debug.Log($"[AddressablePrefabDemo] Spawned '{AssetKey}' through Framework.Asset.AssetLoader.");
            }
            catch (Exception exception)
            {
                spawnRequested = false;
                Debug.LogException(exception);
            }
        }
    }

}
